{% set name = "inline-html" %}
{% set version = "1.0.0" %}
{% set sha256 = "b8291390cc7ef5337cd0eaa8ff160585a7eb67d148b32e46cb744b02d15fc5aa" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
  sha256: {{ sha256 }}
  patches:
    - setup-py.patch

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv"
  entry_points:
    - inline-html = inline_html.inline_html:inline_resources
  noarch: python

requirements:
  host:
    - python
    - pip
  run:
    - python
    - setuptools
    - cssutils
    - click
    - lxml

test:
  imports:
    - inline_html
  commands:
    - inline-html --help

about:
  home: https://github.com/zopyx/inline-html
  license: GPL-2.0
  license_family: GPL
  license_file: LICENSE.txt
  summary: >
    Python script for inlining CSS stylesheets and conversion of resources
    to data-uri.
  description: |
    This script parses an input HTML and, inlines all images in <img> tags
    with data-uri, inlines all external stylesheets references using
    <link rel="stylesheet" type="text/css"...> replaces all CSS references
    to external files (url(..)) with data-uri
  dev_url: https://github.com/zopyx/inline-html

extra:
  recipe-maintainers:
    - holtgrewe
