travis:
  secure:
    BINSTAR_TOKEN: W6vxPZFObYGkqXkUyxp4wv2znMn/pGx7T7r1egdcKweuAFrqIsFkX0fVq08kuXZZBEQyZUW0Ivv68xstGUFA2meqRVOvTQ6Lp9BXd2LNctOJaEWM9NThvKKZWYkQf/el1Q7Sc0XE4rxNAzbDmdXi863+MrMRVOZldu7u+6D9IxGyAlnHpD6NnGLHGy7i18WVBtpoY7HD522WqB73ZWRvWLtoiRXJEMfR2nZ3P3QJc4gfXmZN+oigDRcE21XdP6BKPkrhgYyA251wiRV4NaqebkiKm1hZumjU1YioLzLaf/ylY1bLeJA1I+ae14UXPNWPSa/P06yJRQzF5MRUPRsCHtsLpMnRV9A0EI9HGgcVGs7CuFEJYGlBQfutN3JkOADEmaDYA9lyQ0NnaUbxldLKx7QkgHpEXssss0iH7JzFCus5xsYCh3ccUI+INKCDl5+Ye2Hdao+EzFqw/lT7yuuM2iwEsEgt2brx8DF/YaZHeMMkL0yUeKXL15DH5cHv4vis/L9zGbws53SjYTjxSm6Y2XczQVd7KmJX9InNEO/0ObTvVKyTg8nTsC3WQQRn9gvaeZtO2Iprkv+o9x5g5VPqh/aE8kUzMAwB32grEFtKCUVEs3VEQ0LC6kYb4vK1Jf3Jn/elh189VGV6DUeaHb6z1Ag2VdUckpMkl8oOU8EpQVc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
