travis:
  secure:
    BINSTAR_TOKEN: liVD3yoGn2vULBH50d+2LuJPzZkRS5Xm7zlzx4IPnTw0s6GwqVqS7KJpDQpcUO8MZpqbakouprYlEKkD4hp9ovxcM1z5ZYb1kBFw0Rrsg35dJ7AUVWYYPPuObrFDvq+QClqhE4PqFZJFG8t79KeuikWO+/bUhPD4WaW8TphPA1JqGj/hjozE7zB0ere1bRzjfRX87j2SI9o6MVdW65TlKZkNOu846tw+F+4O3n74WM3oZVJcd9XZH+ork1JqhLtDKxSDUhKmDu9FqNT9VNs4eppcRJ3wOQum+2H9qwvu5NouDyv9leszsbUJW+o5fNOQFQehMZlDqByKYFSCq3qI5m4u5iUlEchziO163gGqMT85Ftc3j6wVvnqFaNIcSCYXsjr00OmI6EdInTEhmw7oUi9vj2qhDylPykj8DsKGTvskRLMO8z3w9HZlbD6bThTEeanNUifulgO2ml8i2UVy+5wbT/kgMK+ELHOjyyMCV7IZPXTKu0h9PVMo6i1lDWgb+TS3S14J5ViNYA6NjUmQ+K82Olpxvh5UVNzmS2aepy0EfiwPPD2QkC9fuvi/qBtY2RkVkydHr6HhXbxjHxvRms4+kdZOAZKtkVusvD+OYigb+t9XSBQF0nNp8x5IqUBHKi3BqDweXE2yROuxPh2Fw9epqziO7g5wNkQqjQhqFxM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
